//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ffmpeg_mini_gui.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ffmpeg_mini_gui.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ::@echo off
        ///echo ffmpeg-mini-gui
        ///echo -------------------
        ///echo.
        ///
        ///::Change code page to Unicode
        ///chcp 65001
        ///
        ///{command}
        ///
        ///pause.
        /// </summary>
        internal static string cmd_universal {
            get {
                return ResourceManager.GetString("cmd_universal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap down32 {
            get {
                object obj = ResourceManager.GetObject("down32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ::@echo off
        ///echo ffmpeg-mini-gui
        ///echo -------------------
        ///echo.
        ///
        ///::Change code page to Unicode
        ///chcp 65001
        ///
        ///{ffmpeg} {refer} -i &quot;{url}&quot; -c copy &quot;{output}.mp4&quot;
        ///
        ///
        ///@echo.
        ///@echo when no errors - destination video saved to {output}
        ///@echo.
        ///pause
        ///exit.
        /// </summary>
        internal static string download_m3u8 {
            get {
                return ResourceManager.GetString("download_m3u8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ::@echo off
        ///echo ffmpeg-mini-gui
        ///echo -------------------
        ///echo.
        ///
        ///::Change code page to Unicode
        ///chcp 65001
        ///
        ///set bitrate=*bitrate*
        ///set preset=*preset*
        ///set output=*output*
        ///set filters=*filters*
        ///set ffmpeg=*curr*\ffmpeg.exe
        ///
        ///%ffmpeg% -i &quot;*video*&quot;%filters%-b:v %bitrate% %timecut% -preset %preset% -vcodec libx264 -acodec copy &quot;%output%&quot;
        ///
        ///@echo.
        ///@echo when no errors - destination video saved to %output%
        ///@echo.
        ///::pause
        ///timeout /t 10
        ///exit.
        /// </summary>
        internal static string onepassCMD {
            get {
                return ResourceManager.GetString("onepassCMD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ::@echo off
        ///echo ffmpeg-mini-gui
        ///echo -------------------
        ///echo.
        ///
        ///::Change code page to Unicode
        ///chcp 65001
        ///
        ///set bitrate=*bitrate*
        ///set preset=*preset*
        ///set output=*output*
        ///set filters=*filters*
        ///set ffmpeg=*curr*\ffmpeg.exe
        ///
        ///%ffmpeg% -y -i &quot;*video*&quot;%filters%-b:v %bitrate% %timecut% -preset %preset% -vcodec libx264 -pass 1 -an -f mp4 NUL
        ///%ffmpeg% -i &quot;*video*&quot;%filters%-b:v %bitrate% %timecut% -preset %preset% -vcodec libx264 -pass 2 -acodec copy &quot;%output%&quot;
        ///
        ///@echo.
        ///@echo when no errors - destinat [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string twopassCMD {
            get {
                return ResourceManager.GetString("twopassCMD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap up32 {
            get {
                object obj = ResourceManager.GetObject("up32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap yt_dlp16 {
            get {
                object obj = ResourceManager.GetObject("yt-dlp16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
